version: '3.8'
services:
  micro_service:
    build: .
    image: 'micro_service'
    container_name: 'micro_service'
    ports:
      - '3000:3000'
    volumes: 
      - micro_root_folder:/app/uploads
    env_file:
      - '.db.env'
      - '.micro.env'
    networks:
      - micronet
  micro_db:
    image: 'mongo'
    container_name: 'micro_db'
    ports: #we need this for accessing db from outside!(For Testing)
      - '4040:27017'
    volumes: 
      - micro_db_data:/data/db
    env_file: 
      - '.db.env'
    networks:
      - micronet
volumes: 
  micro_db_data:
  micro_root_folder:
networks:
  micronet:
